baseURL = "https://docs.jsonhoist.org/"
languageCode = "en-us"
title = "JsonHoist"
theme = "hugo-theme-docdock-master"
themesdir = "."

[params]
editURL ="https://github.com/uweschaefer/factcast/edit/master/factcast-site/documentation/content/"
noHomeIcon = false
noSearch = false



[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "Github repo <i class='fa fa-github'></i>"
identifier = "github"
url = "https://github.com/uweschaefer/jsonhoist/"
weight = 1


[[menu.shortcuts]]

name = "Legal / Impressum"
identifier = "legal"
url = "/imprint"
weight = 999

